### ISSUE TITLE
CodeRepository.codeIsActive() is throwing RuntimeException when active field is zero (0)

### ISSUE THREAD

**Issue by sashirestela** [siteadmin/code-validator-api#50]
## Problem

In the interface CodeRepository, we have the method:

```
@Query("SELECT c.active FROM Code c WHERE c.active = 1 AND c.code = :code and c.codeSystem in (:codesystems)")
boolean codeIsActive(@Param("code")String code, @Param("codesystems")Set<String> codesystems);
```

When **c.active** is different to 1 the query will return null and Java cannot parse null to boolean, so it throws a RuntimeException:

```
2018-06-12 21:13:54.057 ERROR 9460 --- [http-nio-8081-exec-2] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/api/ccda] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Unknown error: Null return value from advice does not match primitive return type for: public abstract boolean org.sitenv.vocabularies.validation.repositories.CodeRepository.codeIsActive(java.lang.String,java.util.Set)] with root cause

org.springframework.aop.AopInvocationException: Null return value from advice does not match primitive return type for: public abstract boolean org.sitenv.vocabularies.validation.repositories.CodeRepository.codeIsActive(java.lang.String,java.util.Set)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:221) ~[spring-aop-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at com.sun.proxy.$Proxy103.codeIsActive(Unknown Source) ~[?:?]
	at org.sitenv.vocabularies.validation.validators.nodetypes.CodeSystemCodeValidator.validateNode(CodeSystemCodeValidator.java:74) ~[codevalidator-api-1.0.13.jar:?]
	at org.sitenv.vocabularies.validation.services.VocabularyValidationService.validate(VocabularyValidationService.java:69) ~[codevalidator-api-1.0.13.jar:?]
	at org.sitenv.vocabularies.validation.services.VocabularyValidationService.validate(VocabularyValidationService.java:49) ~[codevalidator-api-1.0.13.jar:?]
```

## Possible Solutions

Remove the condition c.active = 1 in the interface query and use implicit or explicit conversion from integer to boolean

a) Implicit conversion:
`SELECT c.active FROM Code c WHERE c.code = :code and ...`

b) Explicit conversion:
`SELECT CAST(c.active, SQL_BOOLEAN) FROM Code c WHERE c.code = :code and ...`

Best regards

Sashir

**Comment by drbgfc** [comment]
Thanks for this detailed explanation. Any chance you have an XML document or snippet which I can reproduce the issue with?

**Comment by drbgfc** [comment]
Note: Ended up using the Implicit conversion in addition to the above fix first fix did not address all cases. Thanks for your input.
